Fix releasing workflow
This fixes the following failure with the releasing workflow introduced in PR #682.
Since `npm version` creates a new commit, `git config` has to be run beforehand.

```
Error: Command failed: npm version 1.5.1
npm error code 128
npm error An unknown git error occurred
npm error command /usr/bin/git --no-replace-objects commit -m 1.5.1
npm error Author identity unknown
npm error
npm error *** Please tell me who you are.
npm error
npm error Run
npm error
npm error   git config --global user.email "you@example.com"
npm error   git config --global user.name "Your Name"
npm error
npm error to set your account's default identity.
npm error Omit --global to set the identity only in this repository.
npm error
npm error fatal: empty ident name (for <runner@pkrvmf6wy0o8zjz.nkxfvzbbtpnuvczvu5zh20c0sb.dx.internal.cloudapp.net>) not allowed
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-06-05T01_01_00_260Z-debug-0.log
```

https://github.com/stylelint/vscode-stylelint/actions/runs/15455942982/job/43508136978#step:9:30