Refine releasing workflow
I found that we should change the releasing workflow implemented in PRs:
- #682
- #684

Because there isn't a good way to bypass the repository rule to prevent direct commits to the main branch during the workflow.

See the error in the workflow log:
https://github.com/stylelint/vscode-stylelint/actions/runs/15457510196/job/43512350801

```
Published stylelint.vscode-stylelint v1.5.1.
remote: error: GH013: Repository rule violations found for refs/heads/main.
remote: Review all repository rules at https://github.com/stylelint/vscode-stylelint/rules?ref=refs%2Fheads%2Fmain
remote:
remote: - 10 of 10 required status checks are expected.
remote:
remote: - Changes must be made through a pull request.
remote:
To https://github.com/stylelint/vscode-stylelint
 * [new tag]         v1.5.1 -> v1.5.1
 ! [remote rejected] main -> main (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/stylelint/vscode-stylelint'
```

There are a few workarounds to prevent the error, such as introducing PAT, but I don't want to do that for security and maintainability.

That's why I suggest the workflow change. In summary:
- Humans manually need to update the `version` field in `package.json`, push a commit, and create a pull request to release a new version.
- After merging the pull request, the same person manually needs to trigger the releasing workflow.
- Then, the workflow will automatically publish the extension and create a GitHub release.

By doing this, I think we can avoid the error in GitHub Actions.